LOGIN_PAGE_BUTTON = '//div[contains(@class, "responseHead-module-button")]'
EMAIL_FIELD = '//input[@name="email"]'
PASSWORD_FIELD = '//input[@name="password"]'
LOGIN_AUTHFORM_BUTTON = '//div[contains(@class, "authForm-module-button")]'
RIGHT_MODULE_BUTTON = '//div[contains(@class, "right-module-rightButton")]'
RIGHT_MODULE_LOGOUT_BUTTON = '//a[@href="/logout"]'
FIO_FIELD = '//div[@data-name="fio"]/div/input'
PHONE_FIELD = '//div[@data-name="phone"]/div/input'
SAVE_BUTTON = '//div[@class="button__text"]'
SUCCESS_TEXT = '//div[@data-class-name="SuccessView"]/div'
AUDIT_SEGM_BUTTON = '//a[@href="/segments"]'
STATISTICS_BUTTON = '//a[@href="/statistics"]'